# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\source\PyProject\YukisPythonUtilsScripts\src\EasyyibiaoUtils\qtui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 149)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 301, 85))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.format_BTN = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.format_BTN.setObjectName("format_BTN")
        self.gridLayout_2.addWidget(self.format_BTN, 0, 1, 1, 1)
        self.display_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.display_label.setText("")
        self.display_label.setObjectName("display_label")
        self.gridLayout_2.addWidget(self.display_label, 0, 2, 1, 1)
        self.formatSelect_box = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.formatSelect_box.setObjectName("formatSelect_box")
        self.gridLayout_2.addWidget(self.formatSelect_box, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.sourcePath_BTN = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sourcePath_BTN.setObjectName("sourcePath_BTN")
        self.gridLayout.addWidget(self.sourcePath_BTN, 0, 1, 1, 1)
        self.savePath_BTN = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.savePath_BTN.setObjectName("savePath_BTN")
        self.gridLayout.addWidget(self.savePath_BTN, 1, 1, 1, 1)
        self.saveDir_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.saveDir_txt.setObjectName("saveDir_txt")
        self.gridLayout.addWidget(self.saveDir_txt, 1, 0, 1, 1)
        self.soureDir_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.soureDir_txt.setObjectName("soureDir_txt")
        self.gridLayout.addWidget(self.soureDir_txt, 0, 0, 1, 1)
        self.imgsize_layout = QtWidgets.QHBoxLayout()
        self.imgsize_layout.setObjectName("imgsize_layout")
        self.width_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.width_txt.setObjectName("width_txt")
        self.imgsize_layout.addWidget(self.width_txt)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.imgsize_layout.addWidget(self.label)
        self.height_txt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.height_txt.setObjectName("height_txt")
        self.imgsize_layout.addWidget(self.height_txt)
        self.gridLayout.addLayout(self.imgsize_layout, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 340, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyyibiaoFormat - YukiTechSoftware"))
        self.format_BTN.setText(_translate("MainWindow", "format"))
        self.sourcePath_BTN.setText(_translate("MainWindow", "source path"))
        self.savePath_BTN.setText(_translate("MainWindow", "save path"))
        self.label.setText(_translate("MainWindow", "x"))
